<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/5/16
 * Time: 17:39
 * Comment: 文章控制器
 */
namespace app\admin\controller;

use app\common\model\ArticleModel as ArticleModel;
use think\Controller;

class Article extends Controller {

   public function _initialize()
   {
       parent::_initialize(); // TODO: Change the autogenerated stub
       /*$article = new ArticleModel();
       $article->select();*/
   }

   public function index() {
       echo "进入后台";
   }
}