<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/5/16
 * Time: 17:57
 * Comment: 前端基础控制器
 */
namespace app\common\controller;

use think\Cookie;

class Frontend extends BaseController {

    /**
     * 实现初始化方法
     */
    public function __initialize()
    {
        parent::__initialize(); // TODO: Change the autogenerated stub
        //获取web配置
    }
}
